class CreateArtists < ActiveRecord::Migration[4.2]

  def change
    create_table :artists do |t| #added the create_table method and passed the name of the table we want to create as a symbol
      t.string :name
      t.string :genre
      t.integer :age
      t.string :hometown
      #on the left we've given the data type we'd like to cast the column as, and on the right we've given the name we'd like to give the column
      #primary key will be automatically generated by ActiveRecord
    end
  end

end
